# rustup toolchain config. We typically use nightly to enable better formatting and async support.
# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
# what toolchain to use. 
channel="nightly" 

# option to specify a date to pin to a particular release 
# date = "2024-03-19"

# profiles are groups of components to download when installing a toolchain.
# https://rust-lang.github.io/rustup/concepts/profiles.html
# "minimal" includes only the compiler, package manager, and standard lib.
# "default" further includes the formatter, linter, and documentation generator.
profile="default"